// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type ConvertReq struct {
	LongURL string `json:"longUrl" validate:"required"` // validator 参数校验
}

type ConvertResp struct {
	ShortURL string `json:"shortUrl"`
}

type ShowReq struct {
	ShortURL string `path:"shortURL" validate:"required"`
}

type ShowResp struct {
	LongURL string `json:"longUrl"`
}
